params:
  last_updated_ai_data_center_studies_centraltable_28012025: February 26, 2025 at 20:32
  last_updated_dc_energy_use_pue: February 13, 2025 at 12:15
  last_updated_dcewm_energystudiesdata: September 09, 2025 at 14:59
  last_updated_dcewm_puedataset: October 06, 2025 at 15:02
  last_updated_dcewm_wuedataset: October 06, 2025 at 15:05
  last_updated_modules: April 02, 2025 at 10:55