---
format: 
  html:
    toc: true
    toc-depth: 4
    toc-title: " "
other-links:
  - text: "📊 Explore PUE/WUE Data"
    href: "/pue-wue"
    #icon: "fas fa-chart-bar"
author:
  - name: "Eric Masanet"
    affiliation: "Industrial Sustainability Laboratory, University of California, Santa Barbara"
    email: "email@dcewm.org"
    orcid: "0000-0000-0000-0000"
  - name: "Co-author Name"
date: "2025-08-12"
google-scholar: true

citation:
  type: webpage
  title: "PUE FAQs/Methodology"
  author: 
    - "Eric Masanet"
    - "Co-author Name"
  url: "https://dcewm.org/"
---

### PUE FAQs/Methodology

#### What is PUE?

PUE stands for power usage effectiveness.  First introduced by @greenGridPUE2007 in 2007, it is a common energy performance metric utilized by the data center industry.  PUE is calculated by dividing the total amount of energy consumed by a data center by the amount of energy consumed by its IT equipment alone. Lower values of PUE indicate that smaller shares of a data center’s energy use go to its non-IT infrastructure systems (such as cooling and power supply systems). The theoretical minimum value of PUE for any data center is 1.0.

#### Is PUE still relevant?

PUE only captures the shares of IT and non-IT energy used by a data center. Therefore, PUE shouldn’t be interpreted as a stand-alone measure of a data center’s energy efficiency or sustainability [@masanetLowCarbon2013]. That said, PUE is still relevant to multiple stakeholders for several reasons:
- It is easy to measure for most data centers.
- When applied to a single data center, trends in PUE can be useful for understanding and tracking infrastructure energy efficiency.
- It is widely used by energy modelers to quantify the infrastructure system energy use of the data center sector.
- Even low PUE values translate into substantial grid loads at large data centers, giving value to its visibility.
- It is a simple metric that policy makers can use [@vertivBeijing2021] to incentivize or require energy-efficient infrastructure systems.

...

#### References

::: {#refs}
:::

